apiVersion: v1
kind: ConfigMap
metadata:
  name: kafbat-ui-helm-values
data:
  KAFKA_CLUSTERS_0_NAME: "access-kafka-cluster"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "access-kafka-cluster-kafka-bootstrap:9092"
  KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "PLAINTEXT"
  AUTH_TYPE: "DISABLED"
  MANAGEMENT_HEALTH_LDAP_ENABLED: "FALSE"
