# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: EUPL-1.2

SHELL := /bin/bash
.DEFAULT_GOAL := help

K3S_REGISTRY   ?= registry.dev.local:8443
K3S_NAMESPACE  ?= wallet-hsm
K3S_TAG        ?= k3s
K3S_GITOPS_DIR ?= ../wallet-accessmechanism-gitops

.PHONY: copy-tokens verify-tokens fix-permissions copyright build-verify verify-docker \
	up build down logs help \
	k3s-deploy k3s-rollout-now k3s-seal-secrets k3s-setup

## copy-tokens: copy SoftHSM tokens from running hsm-worker container to host
copy-tokens:
	@echo "Copying tokens from container..."
	docker compose cp hsm-worker:/myuser/softhsm/tokens softhsm-tokens
	@echo "Copy complete."

## verify-tokens: list copied SoftHSM token files on host
verify-tokens:
	ls -la softhsm-tokens/

## fix-permissions: fix ownership of softhsm-tokens/ (run if Permission Denied on host)
fix-permissions:
	sudo chown -R $(shell id -u):$(shell id -g) softhsm-tokens

## copyright: annotate source files with REUSE copyright headers
copyright:
	git ls-files -z -- '*.rs' '*.toml' '*.sh' '*.yaml' '*.yml' '*.py' 'Makefile' '*Makefile' '*Dockerfile' '*Containerfile' 'justfile' | \
		xargs -0 reuse annotate \
			--license EUPL-1.2 \
			--copyright "Digg - Agency for Digital Government" \
			--year "$$(date +%Y)" \
			--skip-unrecognised \
			--skip-existing
	reuse lint

## build-verify: build CI verification container
build-verify:
	docker build -t hsm-verify -f ci/Dockerfile .

## verify-docker: run full CI verification suite in Docker
verify-docker: build-verify
	docker run --rm -v "$(CURDIR):/src" hsm-verify

## up: start Docker Compose services
up:
	docker compose up -d

## build: build Docker Compose images
build:
	docker compose build

## down: stop Docker Compose services
down:
	docker compose down

## logs: tail hsm-worker container logs
logs:
	docker compose logs -f hsm-worker

## k3s-seal-secrets: seal .env.softhsm + .env.opaque into gitops sealed-secrets.yaml
## Re-run after cluster rebuild (new sealed-secrets key) or when .env files change.
## Requires: k3s-environment 'make up' done, kubeseal shim in PATH.
k3s-seal-secrets:
	@set -euo pipefail; \
	_seal() { \
	  local name=$$1 file=$$2 args=(); \
	  while IFS= read -r line || [[ -n "$$line" ]]; do \
	    [[ -z "$$line" || "$$line" =~ ^[[:space:]]*\# ]] && continue; \
	    args+=(--from-literal="$$line"); \
	  done < "$$file"; \
	  kubectl create secret generic "$$name" \
	    --namespace=$(K3S_NAMESPACE) --dry-run=client -o yaml "$${args[@]}" | \
	  kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system \
	    --namespace=$(K3S_NAMESPACE) --format=yaml; \
	}; \
	{ \
	  printf '# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government\n'; \
	  printf '# SPDX-License-Identifier: EUPL-1.2\n'; \
	  printf '# Generated by: make k3s-seal-secrets. Re-run after cluster rebuild or .env changes.\n'; \
	  _seal hsm-worker-softhsm .env.softhsm; \
	  _seal hsm-worker-opaque .env.opaque; \
	} > "$(K3S_GITOPS_DIR)/apps/hsm-worker/sealed-secrets.yaml"
	@echo "Sealed: $(K3S_GITOPS_DIR)/apps/hsm-worker/sealed-secrets.yaml"

## k3s-deploy: build + push :k3s images to local registry (no pod restart)
## Run k3s-rollout in wallet-accessmechanism-gitops to trigger the actual rollout.
## Usage: make k3s-deploy [K3S_NAMESPACE=wallet-hsm] [K3S_TAG=k3s]
k3s-deploy:
	docker build -t $(K3S_REGISTRY)/diggsweden/rust-wallet-bff:$(K3S_TAG) \
	  -f wallet-bff/Containerfile .
	docker push $(K3S_REGISTRY)/diggsweden/rust-wallet-bff:$(K3S_TAG)
	docker build -t $(K3S_REGISTRY)/diggsweden/rust-hsm-worker:$(K3S_TAG) \
	  -f hsm-worker/Containerfile .
	docker push $(K3S_REGISTRY)/diggsweden/rust-hsm-worker:$(K3S_TAG)

## k3s-rollout-now: force immediate pod restart, bypassing Flux gitops cycle
## Use after k3s-deploy when you don't want to wait for Flux reconciliation.
k3s-rollout-now:
	kubectl rollout restart statefulset/wallet-bff statefulset/hsm-worker -n $(K3S_NAMESPACE)
	kubectl rollout status statefulset/wallet-bff statefulset/hsm-worker \
	  -n $(K3S_NAMESPACE) --timeout=5m

## k3s-setup: full tenant init — seal secrets, push+register gitops, deploy images, rollout
## Run once after 'make up' in k3s-environment. Re-run to redeploy after changes.
## Usage: make k3s-setup [K3S_NAMESPACE=wallet-hsm]
k3s-setup: k3s-seal-secrets
	@cd "$(K3S_GITOPS_DIR)" && \
	  git diff --quiet apps/hsm-worker/sealed-secrets.yaml || \
	    git commit -s apps/hsm-worker/sealed-secrets.yaml \
	      -m "chore: seal secrets for $(K3S_NAMESPACE)"
	$(MAKE) -C "$(K3S_GITOPS_DIR)" k3s-push k3s-register
	$(MAKE) k3s-deploy
	$(MAKE) -C "$(K3S_GITOPS_DIR)" k3s-rollout

## help: show this help
help:
	@grep -E '^## ' $(MAKEFILE_LIST) | sed 's/^## //'
