# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: CC0-1.0

FROM eclipse-temurin:21-jdk-jammy AS builder

# Install SoftHSM2, OpenSC (pkcs11-tool) openssl PKCS#11 integration and related tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git autoconf automake libtool pkg-config \
    libpcsclite-dev libssl-dev pcscd \
    curl ca-certificates \
    softhsm2 libsofthsm2 libengine-pkcs11-openssl \
 && rm -rf /var/lib/apt/lists/*

# build OpenSC 0.26.1
WORKDIR /tmp
RUN curl -L -o opensc-0.26.1.tar.gz https://github.com/OpenSC/OpenSC/releases/download/0.26.1/opensc-0.26.1.tar.gz \
 && tar xzf opensc-0.26.1.tar.gz \
 && cd opensc-0.26.1 \
 && ./configure --prefix=/usr --disable-static --without-cmocka \
 && make -j"$(nproc)" \
 && make install \
 && ldconfig
# Install Mastercard pkcs11-tools
RUN curl -L -o /tmp/pkcs11-tools.tar.gz \
       https://github.com/Mastercard/pkcs11-tools/releases/download/v2.6.0/pkcs11-tools-2.6.0.tar.gz \
 && tar xzf pkcs11-tools.tar.gz && cd pkcs11-tools-2.6.0 \
 && ./configure --prefix=/usr \
 && make -j"$(nproc)" \
 && make install && cd /

RUN ARCH=$(dpkg --print-architecture) && \
    MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH) && \
    mkdir -p /install/lib && \
    cp -P /usr/lib/${MULTIARCH}/libpcsclite.so* /install/lib/ && \
    cp -P /usr/lib/${MULTIARCH}/libssl.so* /install/lib/ && \
    cp -P /usr/lib/${MULTIARCH}/libcrypto.so* /install/lib/



WORKDIR /app

COPY r2ps-worker/softhsm/kek.bin /opt/kek.bin
COPY r2ps-worker/softhsm/softhsm2.conf /opt/softhsm2.conf
COPY r2ps-worker/softhsm/softhsm2-p256.conf /opt/softhsm2-p256.conf
COPY r2ps-worker/softhsm/softhsm2-p384.conf /opt/softhsm2-p384.conf
COPY r2ps-worker/softhsm/softhsm2-p521.conf /opt/softhsm2-p521.conf
COPY r2ps-worker/p11-keygen.sh p11-keygen.sh
RUN chmod +x p11-keygen.sh

COPY mvnw ./
COPY .mvn ./.mvn
COPY pom.xml ./
RUN chmod +x ./mvnw
#COPY r2ps-common-domain/pom.xml ./r2ps-common-domain/
#COPY r2ps-worker/pom.xml ./r2ps-worker/
#COPY r2ps-rest-api/pom.xml ./r2ps-rest-api/
# RUN ./mvnw dependency:go-offline -B -s settings.xml
# RUN ./mvnw dependency:go-offline -B

COPY r2ps-common-domain ./r2ps-common-domain
COPY r2ps-worker ./r2ps-worker
COPY r2ps-rest-api ./r2ps-rest-api

# Make mvnw executable
RUN ./mvnw install
RUN ./mvnw package -pl r2ps-worker -am -DskipTests

ENV SOFTHSM2_CONF=/opt/softhsm2.conf
ENV PKCS11LIB=/usr/lib/softhsm/libsofthsm2.so
ENV PKCS11PASSWORD=123456
ENV PKCS11SLOT=0
# Key gen script ENV
ENV PKCS11_MODULE=$PKCS11LIB
#ENV LIBPKCS11=/usr/lib/aarch64-linux-gnu/engines-3/libpkcs11.so

# Init SoftHSM2
RUN softhsm2-util --init-token --slot 0 --label "wallet-keys" \
      --so-pin "1938456231" --pin "123456"

# Import static KEK key to retain keys after image rebuild to match existing key records
RUN pkcs11-tool --module "$PKCS11LIB" \
  --slot-index "$PKCS11SLOT" --login --pin "$PKCS11PASSWORD" \
  --write-object /opt/kek.bin \
  --type secrkey \
  --key-type AES:32 \
  --label kek-1 --id 01 \
  --usage-decrypt --usage-wrap


# Import static KEK key to retain keys after image rebuild to match existing key records
RUN pkcs11-tool --module "$PKCS11LIB" \
  --slot-index "$PKCS11SLOT" --login --pin "$PKCS11PASSWORD" \
  --write-object /opt/kek.bin \
  --type secrkey \
  --key-type AES:32 \
  --label kek-1 --id 01 \
  --usage-decrypt --usage-wrap

#RUN cp /app/r2ps-worker/src/main/resources/application.yaml /config/application.yml

#COPY --from=builder /app/r2ps-worker/target/test-classes /app/target/test-classes
COPY r2ps-worker/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]


