#!/usr/bin/env python3
"""
Post-process HTML generated by json-schema-for-humans:

1. Fix Bootstrap accordion anchor IDs so #hash navigation lands on visible elements.
2. Migrate from Bootstrap 4 + jQuery to Bootstrap 5 (no jQuery required).
3. Replace Expand all / Collapse all data-attribute buttons with vanilla-JS handlers.
4. Inject a navigation helper (expandSection) that uses the Bootstrap 5 Collapse API.

Bootstrap 4 → Bootstrap 5 attribute/class changes applied:
  data-toggle=    → data-bs-toggle=
  data-target=    → data-bs-target=
  data-parent=    → data-bs-parent=
  badge-dark      → text-bg-dark
  pl-5            → ps-5
  text-right      → text-end
"""

import os
import re
import sys

INPUT  = sys.argv[1] if len(sys.argv) > 1 else "docs/domain-model.html"
OUTPUT = sys.argv[2] if len(sys.argv) > 2 else INPUT

with open(INPUT) as f:
    html = f.read()

# ── Step 1: Fix accordion anchor IDs ─────────────────────────────────────────
#
# json-schema-for-humans places id="X" on the Bootstrap collapse *body* div:
#
#     <div id="accordionX">
#       <div class="card-header" id="headingX">   ← always visible
#       <div id="X" class="collapse ...>           ← hidden by default
#
# Navigating to #X lands on a hidden element.
#
# Fix:
#   id="headingX"          → id="X"
#   id="X" class="collapse → id="collapseX" class="collapse
#   data-target="#X"       → data-target="#collapseX"
#   aria-controls="X"      → aria-controls="collapseX"
#   aria-labelledby="headingX" → aria-labelledby="X"

all_ids = set(re.findall(r'id="([^"]+)"', html))

# Find every X where BOTH id="headingX" and id="X" exist.
names_to_fix = sorted(
    x for x in (i[len("heading"):] for i in all_ids if i.startswith("heading"))
    if x in all_ids
)

for x in names_to_fix:
    col = f"collapse{x}"

    # 1. Rename collapse body: id="X" class="collapse..." → id="collapseX" class="collapse..."
    html = re.sub(
        r'(<div\s+)id="' + re.escape(x) + r'"(\s+class="collapse)',
        r'\1id="' + col + r'"\2',
        html,
    )

    # 2. data-target="#X" → data-target="#collapseX"
    html = html.replace(f'data-target="#{x}"', f'data-target="#{col}"')

    # 3. aria-controls="X" → aria-controls="collapseX"
    html = html.replace(f'aria-controls="{x}"', f'aria-controls="{col}"')

    # 4. aria-labelledby="headingX" → aria-labelledby="X"
    html = html.replace(f'aria-labelledby="heading{x}"', f'aria-labelledby="{x}"')

    # 5. Rename heading: id="headingX" → id="X"
    html = html.replace(f'id="heading{x}"', f'id="{x}"')

print(f"Fixed {len(names_to_fix)} accordion anchors → {OUTPUT}")

# ── Step 2: Migrate Bootstrap 4 + jQuery → Bootstrap 5 ───────────────────────

# 2a. Remove jQuery <script> tag entirely.
html = re.sub(
    r'\s*<script\s[^>]*code\.jquery\.com[^>]*></script>',
    '',
    html,
)

# 2b. Replace Bootstrap 4 CSS CDN with Bootstrap 5.
html = re.sub(
    r'<link\s+href="https://(?:stackpath\.bootstrapcdn\.com/bootstrap/[^"]+|cdn\.jsdelivr\.net/npm/bootstrap@[^"]+)/css/bootstrap(?:\.min)?\.css"[^>]*>',
    '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"'
    ' rel="stylesheet"'
    ' integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"'
    ' crossorigin="anonymous">',
    html,
)

# 2c. Replace Bootstrap 4/5 JS CDN with Bootstrap 5 bundle (includes Popper; no jQuery needed).
html = re.sub(
    r'<script\s+src="https://(?:stackpath\.bootstrapcdn\.com/bootstrap/[^"]+|cdn\.jsdelivr\.net/npm/bootstrap@[^"]+)/js/bootstrap(?:\.bundle)?(?:\.min)?\.js"[^>]*></script>',
    '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"'
    ' integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"'
    ' crossorigin="anonymous" defer></script>',
    html,
)

# 2d. Rename Bootstrap 4 data attributes → Bootstrap 5.
html = html.replace('data-toggle=',  'data-bs-toggle=')
html = html.replace('data-target=',  'data-bs-target=')
html = html.replace('data-parent=',  'data-bs-parent=')

# 2e. Rename deprecated utility classes.
html = html.replace('badge-dark',  'text-bg-dark')              # badge colour
html = re.sub(r'\bpl-5\b',        'ps-5', html)                 # padding-start
html = html.replace('text-right',  'text-end')                  # text alignment

# ── Step 3: Replace Expand all / Collapse all buttons ────────────────────────
#
# Bootstrap 5 does not support complex CSS selectors (e.g. ".collapse:not(.show)")
# in data-bs-target for toggling multiple elements at once.  Replace both buttons
# with plain buttons that are wired up by a small JS snippet injected below.

html = re.sub(
    r'<button[^>]+data-bs-toggle="collapse"[^>]+data-bs-target="\.collapse:not\(\.show\)"[^>]*>Expand all</button>',
    '<button class="btn btn-primary" type="button" id="expandAll">Expand all</button>',
    html,
)
html = re.sub(
    r'<button[^>]+data-bs-toggle="collapse"[^>]+data-bs-target="\.collapse\.show"[^>]*>Collapse all</button>',
    '<button class="btn btn-primary" type="button" id="collapseAll">Collapse all</button>',
    html,
)

# ── Step 4: Inject navigation + expand/collapse-all scripts before </body> ───
#
# Remove any previously injected script block (idempotency: allows the script to
# be re-run on already-processed HTML without duplicating the injected code).
html = re.sub(
    r'<script>\s*\n?(?:function expandSection|// Expand a schema).*?</script>\s*\n?(?=</body>)',
    '',
    html,
    flags=re.DOTALL,
)

NAV_SCRIPT = """\
<script>
// Show a collapse element via Bootstrap 5 API, falling back to class toggle.
function _showCollapse(el) {
  if (!el || !el.classList.contains('collapse')) return;
  if (typeof bootstrap !== 'undefined' && bootstrap.Collapse) {
    bootstrap.Collapse.getOrCreateInstance(el, {toggle: false}).show();
  } else {
    el.classList.add('show');
  }
}

// Expand a schema section by its visible heading id.
// Finds the collapse body via the toggle button's data-bs-target attribute
// (reliable regardless of DOM sibling ordering), then also shows every
// ancestor collapse so nested properties become visible.
function expandSection(id) {
  var el = document.getElementById(id);
  if (!el) return;

  // 1. Find the collapse body for this section.
  //    Prefer reading data-bs-target from the toggle button inside this heading.
  var collapseEl = null;
  var btn = el.querySelector('[data-bs-toggle="collapse"][data-bs-target]');
  if (btn) {
    collapseEl = document.querySelector(btn.getAttribute('data-bs-target'));
  }
  // Fallback: nextElementSibling.
  if (!collapseEl) {
    var sib = el.nextElementSibling;
    if (sib && sib.classList && sib.classList.contains('collapse')) {
      collapseEl = sib;
    }
  }
  _showCollapse(collapseEl);

  // 2. Expand every ancestor collapse panel (needed for nested properties).
  for (var p = el.parentElement; p; p = p.parentElement) {
    if (p.classList && p.classList.contains('collapse')) {
      _showCollapse(p);
    }
  }
}

// Handle direct URL navigation (e.g. file:///...#DeviceHsmState).
document.addEventListener('DOMContentLoaded', function() {
  var hash = decodeURIComponent(window.location.hash.slice(1));
  if (hash) {
    expandSection(hash);
    setTimeout(function() {
      var el = document.getElementById(hash);
      if (el) el.scrollIntoView({block: 'start'});
    }, 400);
  }

  // Wire up Expand all / Collapse all buttons.
  var expandBtn = document.getElementById('expandAll');
  if (expandBtn) {
    expandBtn.addEventListener('click', function() {
      document.querySelectorAll('.collapse:not(.show)').forEach(function(el) {
        _showCollapse(el);
      });
    });
  }
  var collapseBtn = document.getElementById('collapseAll');
  if (collapseBtn) {
    collapseBtn.addEventListener('click', function() {
      document.querySelectorAll('.collapse.show').forEach(function(el) {
        if (typeof bootstrap !== 'undefined' && bootstrap.Collapse) {
          bootstrap.Collapse.getOrCreateInstance(el, {toggle: false}).hide();
        } else {
          el.classList.remove('show');
        }
      });
    });
  }
});
</script>
"""
html = html.replace('</body>', NAV_SCRIPT + '</body>', 1)

with open(OUTPUT, "w") as f:
    f.write(html)

# ── Step 5: Replace schema_doc.min.js with vanilla JS + Bootstrap 5 version ──
#
# json-schema-for-humans generates a jQuery-based schema_doc.min.js.
# We replace it entirely with a vanilla JS equivalent that uses the
# Bootstrap 5 Collapse/Tab API instead of jQuery.  The replacement is
# idempotent: if the file already contains our version, we skip the write.

SCHEMA_DOC_JS = (
    # Anchor click handler (event delegation, no jQuery).
    'document.addEventListener("click",function(event){'
    'var anchor=event.target.closest(\'a[href^="#"]\');'
    'if(!anchor)return;'
    'event.preventDefault();'
    'var h=anchor.getAttribute("href");'
    'try{history.pushState({},"",h)}catch(e){}'
    'var id=decodeURIComponent(h.slice(1));'
    'if(id&&typeof expandSection==="function"){'
    'expandSection(id);'
    'setTimeout(function(){var el=document.getElementById(id);if(el)el.scrollIntoView({block:"start"})},400)'
    '}});'
    # flashElement — already vanilla JS in the original.
    'function flashElement(elementId){'
    'var myElement=document.getElementById(elementId);'
    'if(!myElement)return;'
    'myElement.classList.add("jsfh-animated-property");'
    'setTimeout(function(){myElement.classList.remove("jsfh-animated-property")},1e3)}'
    # setAnchor — just update the URL hash.
    'function setAnchor(anchorLinkDestination){'
    'try{history.pushState({},"",anchorLinkDestination)}catch(e){}}'
    # anchorOnLoad — called from <body onload>.
    'function anchorOnLoad(){'
    'var linkTarget=decodeURIComponent(window.location.hash.split("?")[0].split("&")[0]);'
    'if(linkTarget[0]==="#"){linkTarget=linkTarget.substr(1)}'
    'if(linkTarget.length>0){anchorLink(linkTarget)}}'
    # anchorLink — expand target section then walk ancestors.
    # Calls expandSection (defined in the injected NAV_SCRIPT) so that
    # both the section's own collapse and any ancestor collapses are opened.
    'function anchorLink(linkTarget){'
    'if(typeof expandSection==="function"){expandSection(linkTarget)}'
    'var target=document.getElementById(linkTarget);'
    'if(!target)return;'
    'var node=target.parentElement;'
    'while(node){'
    'if(node.classList){'
    'if(node.classList.contains("collapse")&&!node.classList.contains("show")){'
    'if(typeof bootstrap!=="undefined"&&bootstrap.Collapse){'
    'bootstrap.Collapse.getOrCreateInstance(node,{toggle:false}).show()'
    '}else{node.classList.add("show")}}'
    'else if(node.classList.contains("tab-pane")){'
    'var tabTrigger=document.querySelector("a[href=\'#"+node.id+"\']");'
    'if(tabTrigger&&typeof bootstrap!=="undefined"&&bootstrap.Tab){'
    'new bootstrap.Tab(tabTrigger).show()}}'
    'else if(node.getAttribute&&node.getAttribute("role")==="tab"){'
    'if(typeof bootstrap!=="undefined"&&bootstrap.Tab){'
    'new bootstrap.Tab(node).show()}}}'
    'node=node.parentElement}'
    'setTimeout(function(){'
    'var targetElement=document.getElementById(linkTarget);'
    'if(targetElement){'
    'targetElement.scrollIntoView({block:"center",behavior:"smooth"});'
    'setTimeout(function(){flashElement(linkTarget)},500)}},1e3)}\n'
)

js_file = os.path.join(os.path.dirname(os.path.abspath(OUTPUT)), "schema_doc.min.js")
if os.path.exists(js_file):
    with open(js_file) as f:
        existing = f.read()
    if existing != SCHEMA_DOC_JS:
        with open(js_file, "w") as f:
            f.write(SCHEMA_DOC_JS)
        print(f"Replaced {js_file} with vanilla JS + Bootstrap 5 version")
    else:
        print(f"{js_file} already up to date")
