FROM debian:bookworm-slim as runtime-softhsm

RUN apt-get update && apt-get install -y \
    zlib1g \
    libssl3 \
    libsasl2-2 \
    libzstd1 \
    ca-certificates \
    libsofthsm2 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /myuser/softhsm/tokens /myuser/data

RUN useradd -m myuser
RUN chown -R myuser:myuser /myuser

COPY softhsm/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

USER myuser

RUN echo "directories.tokendir = /myuser/softhsm/tokens" > /myuser/softhsm/softhsm2.conf
ENV SOFTHSM2_CONF=/myuser/softhsm/softhsm2.conf
ENV PKCS11LIB=/usr/lib/softhsm/libsofthsm2.so

FROM rust:1.90-bookworm AS builder

RUN apt-get update && apt-get install -y \
    zlib1g zlib1g-dev \
    cmake \
    libssl-dev \
    libsasl2-dev \
    libzstd-dev \
    pkg-config

WORKDIR /app

COPY Cargo.toml ./
COPY src ./src

# Build static binary
RUN cargo build --release

FROM runtime-softhsm

# Copy the binary from builder
COPY --from=builder /app/target/release/hsm-worker /hsm-worker

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/hsm-worker"]
