FROM rust:1.90-bookworm AS builder

RUN apt-get update && apt-get install -y \
    zlib1g zlib1g-dev \
    cmake \
    libssl-dev \
    libsasl2-dev \
    libzstd-dev \
    pkg-config

WORKDIR /app

COPY Cargo.toml ./
COPY src ./src

# Build static binary
RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    zlib1g \
    libssl3 \
    libsasl2-2 \
    libzstd1 \
    ca-certificates \
    libsofthsm2 \
    && rm -rf /var/lib/apt/lists/*

# Copy the binary from builder
COPY --from=builder /app/target/release/rust-r2ps-worker /rust-r2ps-worker
ENV PKCS11LIB=/usr/lib/softhsm/libsofthsm2.so
RUN softhsm2-util --init-token --slot 0 --label "wallet-keys" --so-pin "1938456231" --pin "123456"
ENTRYPOINT ["/rust-r2ps-worker"]
