# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: EUPL-1.2

upstream wallet-bff {
    server wallet-bff-1:8088;
    server wallet-bff-2:8088;
}

server {
    listen 8088;

    location / {
        proxy_pass http://wallet-bff;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
