[book]
title = "R2PS HSM Worker - Domain Model"
authors = ["DIGG"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/diggsweden/wallet-r2ps"
