# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: EUPL-1.2

FROM rust:1.95-bookworm@sha256:adab7941580c74513aa3347f2d2a1f975498280743d29ec62978ba12e3540d3a AS builder

RUN apt-get update && apt-get install -y \
    zlib1g zlib1g-dev \
    cmake \
    libssl-dev \
    libsasl2-dev \
    libzstd-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY hsm-common ./hsm-common
COPY hsm-worker ./hsm-worker
COPY wallet-bff ./wallet-bff
COPY integration-load-tests ./integration-load-tests

RUN cargo build --release -p wallet-bff

FROM debian:bookworm-slim@sha256:f9c6a2fd2ddbc23e336b6257a5245e31f996953ef06cd13a59fa0a1df2d5c252

RUN apt-get update && apt-get install -y \
    zlib1g \
    libssl3 \
    libsasl2-2 \
    libzstd1 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m appuser
USER appuser

COPY --from=builder /app/target/release/wallet-bff /wallet-bff

EXPOSE 8088

CMD ["/wallet-bff"]
