# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: EUPL-1.2

FROM debian:bookworm-slim as runtime-softhsm

RUN apt-get update && apt-get install -y \
    zlib1g \
    libssl3 \
    libsasl2-2 \
    libzstd1 \
    ca-certificates \
    libsofthsm2 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /myuser/softhsm/tokens

RUN useradd -m myuser
RUN chown -R myuser:myuser /myuser/softhsm

COPY hsm-worker/softhsm/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

USER myuser

RUN echo "directories.tokendir = /myuser/softhsm/tokens" > /myuser/softhsm/softhsm2.conf
ENV SOFTHSM2_CONF=/myuser/softhsm/softhsm2.conf
ENV PKCS11LIB=/usr/lib/softhsm/libsofthsm2.so

FROM rust:1.90-bookworm AS builder

RUN apt-get update && apt-get install -y \
    zlib1g zlib1g-dev \
    cmake \
    libssl-dev \
    libsasl2-dev \
    libzstd-dev \
    pkg-config

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY hsm-common ./hsm-common
COPY hsm-worker ./hsm-worker
COPY wallet-bff ./wallet-bff
COPY integration-load-tests ./integration-load-tests

# Build static binary
RUN cargo build --release -p hsm-worker

FROM runtime-softhsm

# Copy the binaries from builder
COPY --from=builder /app/target/release/hsm-worker /hsm-worker
COPY --from=builder /app/target/release/digg-hsm-keytool /usr/local/bin/digg-hsm-keytool

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/hsm-worker"]
