# SPDX-FileCopyrightText: 2025 diggsweden/wallet-r2ps
#
# SPDX-License-Identifier: CC0-1.0

name: OpenSSF Scorecard Analysis

on:
  push:
    branches:
      - main
  schedule:
    # Saturdays at 02:40 UTC
    - cron: "40 2 * * 6"
    # Wednesdays at 02:40 UTC
    - cron: "40 2 * * 3"
  workflow_dispatch:

permissions:
  contents: read # Best Security practice. Jobs only get read as base, and then permissions are added as needed

jobs:
  scorecard-analysis:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: diggsweden/reusable-ci/.github/workflows/security-openssf-scorecard.yml@a89d880d9a859491c09c300428caa17c9644b39b # v2.8.0
    with:
      publish-results: true
